name: firebase_project
description: Firebase_test


publish_to: 'none'

# The following defines the versioon and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  
  firebase_core: ^0.5.3
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.18.4
  fluttertoast: ^7.1.6
  google_fonts: ^0.3.5
  email_validator: ^1.0.5
  flutter_launcher_icons: ^0.8.1
  url_launcher: ^5.7.10
  dropdown_formfield: ^0.1.3
  intl: ^0.16.1

flutter_icons:
  image_path: "images/hr1.png"
  android: ture
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_ham.jpeg

 
